# Generated by Django 5.1.4 on 2025-01-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_top_tens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
